// 由 project.config.json 生成所有包含站点地址的文件:
//   modules/*                 五种客户端订阅文件 (script-path 指向 Worker 自身)
//   src/project.js            页脚链接与源码地址
//   src/assets.generated.js   Worker 运行时直接返回的静态内容 (脚本 + 模块)
//   README.md 订阅区          markers 之间的表格
//
// 修改站点地址请编辑 project.config.json 后重新运行 npm run configure,
// 不要手改任何 generated 文件。
import { readFile, writeFile, readdir, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));

export async function generatedFiles() {
  const config = JSON.parse(await readFile(path.join(root, 'project.config.json'), 'utf8'));
  const site = String(config.site || '').replace(/\/+$/, '');
  if (site) {
    const url = new URL(site);
    if (url.protocol !== 'https:') throw new Error('site 必须是 HTTPS 地址');
    if (url.username || url.password) throw new Error('site 不能包含凭据');
    if (url.search || url.hash) throw new Error('site 不能包含查询串或片段');
    if (url.pathname !== '/') throw new Error('site 必须是站点根地址，例如 https://xxx.workers.dev');
  } else if (!/REPLACE-ME/.test(config.site ?? '')) {
    throw new Error('project.config.json 缺少 site 字段');
  }

  const repoUrl = config.repository ? `https://github.com/${config.repository}` : `${site}/`;
  const moduleRows = [
    ['Surge / Egern', 'sgmodule'],
    ['Quantumult X', 'conf'],
    ['Loon', 'lpx'],
    ['Stash', 'stoverride'],
    ['Shadowrocket', 'module'],
  ];

  const files = new Map();

  // 1. 五种模块: {{SITE}} -> 站点根地址(无尾斜杠)。
  //    同时保留模板原文(带 {{SITE}})供 Worker 使用: 运行时把占位符替换成请求的
  //    origin, 一键部署后零配置即可用; 磁盘上的 modules/ 仅作参考与备用订阅。
  for (const name of await readdir(path.join(root, 'templates/modules'))) {
    const template = (await readFile(path.join(root, 'templates/modules', name), 'utf8')).replaceAll('\r\n', '\n');
    files.set(`modules/${name}`, template.replaceAll('{{SITE}}', site));
    files.set(`@template/${name}`, template);
  }

  // 2. src/project.js: 页面页脚的订阅链接(相对路径, 运行时拼当前 origin)
  const moduleLinks = moduleRows.map(([name, ext]) => ({ name, path: `/modules/wloc.${ext}` }));
  files.set(
    'src/project.js',
    '// Generated by scripts/configure.mjs; edit project.config.json instead.\n' +
      `export const SOURCE_URL = ${JSON.stringify(repoUrl)};\n` +
      `export const SITE_BASE = ${JSON.stringify(site)};\n` +
      `export const MODULE_LINKS = ${JSON.stringify(moduleLinks, null, 2)};\n`,
  );

  // 3. src/assets.generated.js: Worker 直接服务的静态内容。
  //    全部经 JSON.stringify 嵌入, 避免模板串里出现反引号/`${}` 的转义问题。
  const served = [
    ['/wloc.js', 'vendor/wloc.js', 'application/javascript; charset=utf-8'],
    ['/wloc-settings.js', 'vendor/wloc-settings.js', 'application/javascript; charset=utf-8'],
  ];
  for (const [, name] of moduleRows) {
    served.push([`/modules/wloc.${name}`, `@template/wloc.${name}`, 'text/plain; charset=utf-8']);
  }
  const entries = [];
  for (const [route, rel, type] of served) {
    // 模块取模板原文(保留 {{SITE}}, 由 Worker 运行时按请求 origin 替换); vendor/* 从磁盘读
    const content = (files.get(rel) ?? (await readFile(path.join(root, rel), 'utf8'))).replaceAll('\r\n', '\n');
    entries.push(`  ${JSON.stringify(route)}: { content: ${JSON.stringify(content)}, type: ${JSON.stringify(type)} },`);
  }
  // 根证书(仅证书, 无私钥): public/ 由 engine/tools/make-certs.sh 同步。
  // 站点据此分发 CA, 手机不必再从引擎管理页手动取文件。缺文件时不生成路由(返回 404)。
  let caB64 = null;
  try {
    caB64 = (await readFile(path.join(root, 'public/ca.cer'))).toString('base64');
  } catch {
    caB64 = null;
  }

  // 模块图标: 上游原文指向 GitHub Raw, 这里改为自托管, 做到运行时零外部依赖。
  let iconB64 = null;
  try {
    iconB64 = (await readFile(path.join(root, 'public/wloc.jpg'))).toString('base64');
  } catch {
    iconB64 = null;
  }

  // 引擎地址: 写进 Worker 托管的 PAC。手机只拿 PAC 网址, 不再携带 IP ——
  // 电脑 IP 变了只改 project.config.json 重新部署, 手机端零改动。
  const engineHost = String(config.engineHost ?? '').trim();
  const enginePort = Number(config.enginePort ?? 8888);
  if (engineHost && !/^[A-Za-z0-9.-]{1,253}$/.test(engineHost)) {
    throw new Error('engineHost 只允许字母、数字、点和连字符');
  }
  if (engineHost && (!Number.isInteger(enginePort) || enginePort < 1 || enginePort > 65535)) {
    throw new Error('enginePort 必须是 1-65535 的整数');
  }

  files.set(
    'src/assets.generated.js',
    '// Generated by scripts/configure.mjs; edit templates/ or vendor/ instead.\n' +
      '// Worker 对这些路由原样返回 content; 新增路由请同时更新 src/index.js。\n' +
      'export const SERVED_ASSETS = {\n' +
      entries.join('\n') +
      '\n};\n\n' +
      '// 根证书 DER 的 base64(来自 public/ca.cer, 由 engine/tools/make-certs.sh 同步)。\n' +
      '// 这是公开证书, 不含私钥; 私钥始终只在引擎所在机器上。\n' +
      `export const CA_CERT_B64 = ${caB64 === null ? 'null' : JSON.stringify(caB64)};\n\n` +
      '// 模块图标(来自 public/wloc.jpg), 让模块的 icon 字段也自托管, 不再依赖 GitHub Raw。\n' +
      `export const ICON_B64 = ${iconB64 === null ? 'null' : JSON.stringify(iconB64)};\n\n` +
      '// 引擎在局域网里的地址(来自 project.config.json), 供 /wloc.pac 使用。\n' +
      '// 留空表示尚未配置: 此时 PAC 一律直连(不改任何东西), 页面会提示去填。\n' +
      `export const ENGINE_HOST = ${JSON.stringify(engineHost)};\n` +
      `export const ENGINE_PORT = ${JSON.stringify(enginePort)};\n`,
  );

  // 4. 用户使用指南: 注入站点地址, 部署后可直接把链接发给使用者
  const usage = (await readFile(path.join(root, 'templates/USAGE.md'), 'utf8')).replaceAll('\r\n', '\n');
  files.set('docs/USAGE.md', usage.replaceAll('{{SITE}}', site));

  return { config, files };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const { files, config } = await generatedFiles();
  await mkdir(path.join(root, 'modules'), { recursive: true });
  // @template/* 是供 assets 生成用的内存条目, 不落盘
  for (const [name, content] of files) {
    if (name.startsWith('@template/')) continue;
    await writeFile(path.join(root, name), content);
  }
  if (!config.site || /REPLACE-ME/.test(config.site)) {
    console.log(`已更新 ${files.size} 个文件。`);
    console.log('注意: site 仍是占位地址, 模块暂时不可用。部署后请把真实地址填入 project.config.json 并重新运行 npm run configure。');
  } else {
    console.log(`已更新 ${files.size} 个文件, 站点: ${config.site}`);
  }
}
