// 由 project.config.json 生成所有包含站点地址的文件:
//   modules/*                 五种客户端订阅文件 (script-path 指向 Worker 自身)
//   src/project.js            页脚链接与源码地址
//   src/assets.generated.js   Worker 运行时直接返回的静态内容 (脚本 + 模块)
//   README.md 订阅区          markers 之间的表格
//
// 修改站点地址请编辑 project.config.json 后重新运行 npm run configure,
// 不要手改任何 generated 文件。
import { readFile, writeFile, readdir, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));

export async function generatedFiles() {
  const config = JSON.parse(await readFile(path.join(root, 'project.config.json'), 'utf8'));
  const site = String(config.site || '').replace(/\/+$/, '');
  if (site) {
    const url = new URL(site);
    if (url.protocol !== 'https:') throw new Error('site 必须是 HTTPS 地址');
    if (url.username || url.password) throw new Error('site 不能包含凭据');
    if (url.search || url.hash) throw new Error('site 不能包含查询串或片段');
    if (url.pathname !== '/') throw new Error('site 必须是站点根地址，例如 https://xxx.workers.dev');
  } else if (!/REPLACE-ME/.test(config.site ?? '')) {
    throw new Error('project.config.json 缺少 site 字段');
  }

  const repoUrl = config.repository ? `https://github.com/${config.repository}` : `${site}/`;
  const moduleRows = [
    ['Surge / Egern', 'sgmodule'],
    ['Quantumult X', 'conf'],
    ['Loon', 'lpx'],
    ['Stash', 'stoverride'],
    ['Shadowrocket', 'module'],
  ];

  const files = new Map();

  // 1. 五种模块: {{SITE}} -> 站点根地址(无尾斜杠)
  for (const name of await readdir(path.join(root, 'templates/modules'))) {
    const template = (await readFile(path.join(root, 'templates/modules', name), 'utf8')).replaceAll('\r\n', '\n');
    files.set(`modules/${name}`, template.replaceAll('{{SITE}}', site));
  }

  // 2. src/project.js: 页面页脚的订阅链接
  const moduleLinks = moduleRows.map(([name, ext]) => ({ name, url: `${site}/modules/wloc.${ext}` }));
  files.set(
    'src/project.js',
    '// Generated by scripts/configure.mjs; edit project.config.json instead.\n' +
      `export const SOURCE_URL = ${JSON.stringify(repoUrl)};\n` +
      `export const SITE_BASE = ${JSON.stringify(site)};\n` +
      `export const MODULE_LINKS = ${JSON.stringify(moduleLinks, null, 2)};\n`,
  );

  // 3. src/assets.generated.js: Worker 直接服务的静态内容。
  //    全部经 JSON.stringify 嵌入, 避免模板串里出现反引号/`${}` 的转义问题。
  const served = [
    ['/wloc.js', 'vendor/wloc.js', 'application/javascript; charset=utf-8'],
    ['/wloc-settings.js', 'vendor/wloc-settings.js', 'application/javascript; charset=utf-8'],
  ];
  for (const [, name] of moduleRows) {
    served.push([`/modules/wloc.${name}`, `modules/wloc.${name}`, 'text/plain; charset=utf-8']);
  }
  const entries = [];
  for (const [route, rel, type] of served) {
    // modules/* 直接取内存里第 1 步的生成结果; vendor/* 从磁盘读
    const content = (files.get(rel) ?? (await readFile(path.join(root, rel), 'utf8'))).replaceAll('\r\n', '\n');
    entries.push(`  ${JSON.stringify(route)}: { content: ${JSON.stringify(content)}, type: ${JSON.stringify(type)} },`);
  }
  files.set(
    'src/assets.generated.js',
    '// Generated by scripts/configure.mjs; edit templates/ or vendor/ instead.\n' +
      '// Worker 对这些路由原样返回 content; 新增路由请同时更新 src/index.js。\n' +
      'export const SERVED_ASSETS = {\n' +
      entries.join('\n') +
      '\n};\n',
  );

  // 4. README 订阅区
  const readme = (await readFile(path.join(root, 'README.md'), 'utf8')).replaceAll('\r\n', '\n');
  const rows = [
    '<!-- subscriptions:start -->',
    '| 客户端 | 模块订阅地址 |',
    '| --- | --- |',
    ...moduleLinks.map(({ name, url }) => `| ${name} | [${url}](${url}) |`),
    '',
    `选点页面：[${site}/](${site}/) 。`,
    '',
    `[浏览源码](${repoUrl})`,
    '<!-- subscriptions:end -->',
  ].join('\n');
  if (!readme.includes('<!-- subscriptions:start -->') || !readme.includes('<!-- subscriptions:end -->')) {
    throw new Error('README 缺少订阅区标记');
  }
  files.set('README.md', readme.replace(/<!-- subscriptions:start -->[\s\S]*?<!-- subscriptions:end -->/, rows));

  // 5. 用户使用指南: 同样注入站点地址, 部署后可直接把链接发给使用者
  const usage = (await readFile(path.join(root, 'templates/USAGE.md'), 'utf8')).replaceAll('\r\n', '\n');
  files.set('docs/USAGE.md', usage.replaceAll('{{SITE}}', site));

  return { config, files };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const { files, config } = await generatedFiles();
  await mkdir(path.join(root, 'modules'), { recursive: true });
  for (const [name, content] of files) await writeFile(path.join(root, name), content);
  if (!config.site || /REPLACE-ME/.test(config.site)) {
    console.log(`已更新 ${files.size} 个文件。`);
    console.log('注意: site 仍是占位地址, 模块暂时不可用。部署后请把真实地址填入 project.config.json 并重新运行 npm run configure。');
  } else {
    console.log(`已更新 ${files.size} 个文件, 站点: ${config.site}`);
  }
}
