// Generated by scripts/configure.mjs; edit project.config.json instead.
export const SOURCE_URL = "https://REPLACE-ME.workers.dev/";
export const SITE_BASE = "https://REPLACE-ME.workers.dev";
export const MODULE_LINKS = [
  {
    "name": "Surge / Egern",
    "path": "/modules/wloc.sgmodule"
  },
  {
    "name": "Quantumult X",
    "path": "/modules/wloc.conf"
  },
  {
    "name": "Loon",
    "path": "/modules/wloc.lpx"
  },
  {
    "name": "Stash",
    "path": "/modules/wloc.stoverride"
  },
  {
    "name": "Shadowrocket",
    "path": "/modules/wloc.module"
  }
];
